module V1
  class BalanceController < ApplicationController
  
    def show
    
      card_number = params[:id]
    
      @data = nil
      url = "http://200.46.245.230:8080/PortalCAE-WAR-MODULE/SesionPortalServlet?accion=6&NumDistribuidor=99&NomUsuario=usuInternet&NomHost=AFT&NomDominio=aft.cl&Trx=&RutUsuario=0&NumTarjeta=" + card_number +  "&bloqueable="
    
      puts "Getting card data from: " + url
    
      doc = Nokogiri::HTML(open(url))
    
      # just uncomment to checkout what a piece of HTML crap is generated by MiBus
      #puts doc.inspect    
    
      # Among the HTML filth, we are looking for the <tr> with the class .verdanabold-ckc
      raw_data = doc.css('.verdanabold-ckc')
    
      #puts raw_data
      # if number of items is >5 the card number does not have a contract or they may have changed the HTML
      if raw_data.length < 5
        puts "raw_data: incorrect card number: " + card_number
      else 
        # on the raw_data array evens have the name, odds have the values
        @data = {
          card_number: raw_data[1].text,
          contract_status: raw_data[3].text,
          balance:  raw_data[5].text,
          last_usage: raw_data[7].text
        }
      end
    
      if ! @data.nil?
          render :json => {:status => "success", :data => @data}
      else 
          render_json_fail(:unprocessable_entity, ['¡Chuuleta! El número de tarjeta parece no existir. Por favor, revisa si es correcto.'])
      end
          
    end # index
  end # class
end